server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - "GET"
              - "POST"
              - "PATCH"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: todo-service
          uri: http://demo2:8080
          predicates:
            - Path=/api/todos/**
        - id: user-service
          uri: http://demo1:8080
          predicates:
            - Path=/api/users/**



