server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ""
            allowedMethods:
              - "GET"
              - "POST"
              - "PATCH"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: todo-service
          uri: http://localhost:8082
          predicates:
            - Path=/todos/**
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**



